### ISSUE TITLE
Ansible.cfg instruction 

### ISSUE THREAD

**Issue by danieltudares** [moreati/ansible_callback_experiments#1]
Hi, thanks for creating this module, I love Rich so using it with ansible it's great. 

In your installation instruction on the README.md file you ask to add `stdout=moreati.rich` however this didn't work for me, I had to do `moreati.rich.rich` to make it work. 

This is the error I got using the instruction:
```
ERROR! Invalid callback for stdout specified: moreati.rich
```

I'm using `Ansible-core 2.12.2`

**Comment by moreati** [comment]
Thanks, should be fixed in 0.2.0, just released
